version: '3.1'

services:

  mongo:
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: frank

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: frank
      ME_CONFIG_MONGODB_URL: mongodb://admin:frank@mongo:27017/
  
  catalog-server:
    build: .
    restart: always
    ports:
      - 5000:80
      - 5001:443
    environment:
      MongoDB__Host: mongo
    depends_on:
      - mongo